/* eslint-disable @next/next/no-page-custom-font */
import NavBar from '@/components/Header/NavBar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <NavBar />
        <div className='flex justify-center items-center p-24'>
          {children}
        </div>
      </body>
    </html>
  )
}
